### ISSUE TITLE
Optimistic operator too specific "~> x.x.0" does not update minor version 

### ISSUE THREAD

**Issue by WesleyDRobinson** [CleverTap/clevertap-segment-ios#1]
Minor version updates to Segment's `analytics-ios` are not being pulled in the current implementation.
Recommended fix: [update podspec](https://github.com/CleverTap/clevertap-segment-ios/blob/master/Segment-CleverTap.podspec#L21
) `~> 3.0.0` to `~> 3.0`:

[reference Cocoapods](https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions):
`~> 0.1.2' Version 0.1.2 and the versions up to 0.2, not including 0.2 and higher`

First noted in a Segment Community post:
https://community.segment.com/t/m2mcjv

**Comment by pwilkniss** [comment]
fixed, thanks for the heads up.
