### ISSUE TITLE
UI Main Thread Bug

### ISSUE THREAD

**Issue by dtroupe18** [CleverTap/clevertap-segment-ios#14]
Hi - It looks like the `_handlePushNotification` function inside `CleverTap.m` is accessing `[UIApplication applicationState]` off of the main thread. I am able to consistently reproduce this error by sending a push notification to the app while it's in the foreground. This bug doesn't seem to have any impact on the outcome though. Notifications are still presented and the analytics are still sent. 

![Screen Shot 2020-09-17 at 11 28 39 AM](https://user-images.githubusercontent.com/15720032/93512669-7d2e4f00-f8d9-11ea-9023-595b03c74fab.png)

**Comment by ygit** [comment]
Thanks @dtroupe18 for reporting the behaviour. 
We'll improvise it in an upcoming release soon.

**Comment by Aditi3** [comment]
hi @dtroupe18 

Aforementioned enhancement has been released in the latest version of SDK.
Release Link: https://github.com/CleverTap/clevertap-segment-ios/releases/tag/1.1.7

Thanks for your patience.
