### ISSUE TITLE
Compile error when updating to Segment 4.1.1, 'Analytics' framework was renamed to 'Segment' in Segment 4.1.1

### ISSUE THREAD

**Issue by leandromperez** [CleverTap/clevertap-segment-ios#17]
After a pod update:
- Installing Analytics 4.1.1 (was 4.0.5)
- Installing Segment-CleverTap 1.1.7
![Captura de Pantalla 2020-11-09 a la(s) 09 48 49](https://user-images.githubusercontent.com/104836/98548777-b00d1780-2278-11eb-9246-b7e73c57a877.png)

Changing 'Analytics' to 'Segment' where it corresponds, seems to fix the issue:
E.g. `#import <Segment/SEGAnalyticsUtils.h>` instead of `#import <Analytics/SEGAnalyticsUtils.h>`

**Comment by Aditi3** [comment]
Hi @leandromperez 

I quickly checked the release notes of Segment Analytics. Looks like in their version [4.1.0](https://github.com/segmentio/analytics-ios/releases/tag/4.1.0) they have renamed module from `Analytics` to `Segment`.

Thanks so much for the heads up! We'll add a fix for it in our next release.

**Comment by Aditi3** [comment]
We've shipped the release with the required changes.
Here is the link to the latest release that comes with the fix: https://github.com/CleverTap/clevertap-segment-ios/releases/tag/1.1.8

Thanks again @leandromperez for reporting.

**Comment by leandromperez** [comment]
@Aditi3 Thanks for that. 
Running `pod deintegrate` + `pod update` is installing the latest version of Segment (4.1.1) and Segment-Clevertap (1.1.8). 
But the build is failing because the Analytics.framework is not present in the link phase. It should be trying to link Segment.framework instead right?

```
ld: framework not found Analytics
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Any ideas?

**Comment by Aditi3** [comment]
In my Example Project, Segment.framework is getting linked. 

Link to Starter Application: https://github.com/CleverTap/clevertap-segment-ios/tree/master/ExampleSwift

Try clearing the Xcode and Pod cache?

**Comment by leandromperez** [comment]
Aditi,
Thank you for the response. The problem was an old flag left in Other
Linker Flags. It seems that the old Analytics flag wasn't removed.
Everything is working now.
Best,
Leandro
