### ISSUE TITLE
Can't add pod to project, fails with transitive dependencies error

### ISSUE THREAD

**Issue by elmoswelt** [CleverTap/clevertap-segment-ios#21]
**Describe the bug**
Can't add pod to blank iOS Xcode project.  

`[!] The 'Pods-TestApp' target has transitive dependencies that include statically linked binaries: (Analytics)` 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create blank iOS project
2. Add `pod "Segment-CleverTap"` to pod file
3. Run `pod install`
4. See error : `[!] The 'Pods-TestApp' target has transitive dependencies that include statically linked binaries: (Analytics)` 

**Expected behaviour**
Should install pod without error

**Screenshots**
![Screenshot 2021-04-01 at 14 39 00](https://user-images.githubusercontent.com/1063210/113295070-01857400-92f8-11eb-86d0-267b0ed936c1.png)

![Screenshot 2021-04-01 at 14 39 25](https://user-images.githubusercontent.com/1063210/113295120-119d5380-92f8-11eb-9354-da82d5780eac.png)

**Environment (please complete the following information):**
 - Xcode version: [Version 12.4 (12D4e)]
 - CleverTap SDK Version: [3.9.2]
 - Device: [n/a]
 - OS: [e.g. iOS 14]

**Possible Solution**
unknown

**Comment by Aditi3** [comment]
This looks like a problem with Analytics. Reported at https://github.com/segmentio/analytics-ios/issues/991.

Meanwhile, can you try downgrading Analytics to version 4.1.2 or below and see if that solves the problem for you?

**Comment by Aditi3** [comment]
Closing this issue because the Analytics team addressed the aforementioned issue in their [latest release](https://github.com/segmentio/analytics-ios/releases/tag/4.1.4).
