### ISSUE TITLE
Release new version with dependency clevertap-ios-sdk 4.0  

### ISSUE THREAD

**Issue by atom-wintermute** [CleverTap/clevertap-segment-ios#26]
I want to update `clevertap-ios-sdk` to version 4.0 and we are using it with `Segment` library
So please release new version for `clevertap-segment-ios` with `clevertap-ios-sdk` 4.0 as dependency

**Comment by darshanclevertap** [comment]
@atom-wintermute We are working on this. We will update here when we release this. Expect the release by next week.

**Comment by atom-wintermute** [comment]
thank you!

**Comment by akashvercetti** [comment]
CleverTap Segment iOS SDK v1.2.2 is live.
-Supports iOS SDK v4.0.0
release link: https://github.com/CleverTap/clevertap-segment-ios/releases/tag/1.2.2
