### ISSUE TITLE
Release a new version for CleverTap 4.1.3

### ISSUE THREAD

**Issue by nickbit** [CleverTap/clevertap-segment-ios#29]
Latest versions of CleverTap after 4.1.1 include many bug fixes.
Please update Segment-CleverTap-iOS to allow installing latest version.

Thank you!

**Comment by darshanclevertap** [comment]
@nickbit Yes, this has been planned for the next sprint. We'll keep you updated when we do the release.

**Comment by AishwaryaNanna** [comment]
Hi @nickbit,
New version has been released , supporting latest CleverTap-iOS-SDK.
