### ISSUE TITLE
New release to support CleverTap 4.2.2 and Xcode 14.3

### ISSUE THREAD

**Issue by klumanog-dev** [CleverTap/clevertap-segment-ios#31]
Hi, CleverTap 4.2.2 has been released with fixes for compilation errors for Xcode 14.3+. [v4.2.2](https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/4.2.2)

Please update for segment as well so we can use the latest version. 
Thank you.

**Comment by akashvercetti** [comment]
@klumanog-dev yes we are in the process of releasing fixes for all dependent sdks as soon as possible 👍

**Comment by akashvercetti** [comment]
we have added a fix for this in our latest release v.1.2.5: https://github.com/CleverTap/clevertap-segment-ios/releases/tag/1.2.5 👍
