### ISSUE TITLE
<CleverTapSDK/CleverTap.h> file not found during build

### ISSUE THREAD

**Issue by monoxchd** [CleverTap/clevertap-segment-ios#4]
While trying to implement CleverTap through Segment, I encountered an error that seems common throughout Github issues, which is "<CleverTapSDK/CleverTap.h> file not found" .

I tried every alternative:

- Adding `use_frameworks!` on my Podfile: doesn't work because I am also using Firebase, which conflicts with this flag and does not allow me to build the project.

- Adding `use_module_headers!` on my Podfile: doesn't work because it conflicts with the "glog" podspec and doesn't allow me to build the project; if I use the flag `module_headers: true` on "Segment-CleverTap", "CleverTap-iOS-SDK" and "RNAnalyticsIntegration-CleverTap" it goes back to the "<CleverTapSDK/CleverTap.h> file not found error"

- Adding the CleverTap SDK manually into the project, embedding it on my files: also returns  "<CleverTapSDK/CleverTap.h> file not found error"

- Adding the "@segment/analytics-react-native-clevertap" .xcodeproj into the project, embedding it on my files: also returns "<CleverTapSDK/CleverTap.h> file not found error"

I tried every possible solution, including everything I can find on Github issues or StackOverflow posts and nothing works. Does anyone know how I can solve this? The only solution I found was to change the import on the podfile to `#import <CleverTap-iOS-SDK/CleverTap.h>` on the SEGCleverTapIntegration.m file, but this won't solve my issue.

Here's my final Podfile after every try still not working:

```ruby
platform :ios, '10.0'
install! 'cocoapods',
  :integrate_targets => false,
  :deterministic_uuids => false # remove "Generated duplicate UUIDs" warnings

target '***' do
  #React Dependencies
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for ***
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'ZendeskSDK', '~> 4.0.0'
  pod 'AppsFlyerFramework', '4.10.4'
  pod 'Segment-CleverTap', modular_headers: true
  pod 'CleverTap-iOS-SDK', modular_headers: true

  pod 'react-native-branch', path: '../node_modules/react-native-branch'
  pod 'react-native-appsflyer', path: '../node_modules/react-native-appsflyer'
  pod 'Branch-SDK', path: '../node_modules/react-native-branch/ios'
  pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker/react-native-orientation-locker.podspec'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'

  pod 'RNAnalyticsIntegration-Amplitude', :path => '../node_modules/@segment/analytics-react-native-amplitude'

  pod 'RNAnalyticsIntegration-CleverTap', path: '../node_modules/@segment/analytics-react-native-clevertap', modular_headers: true

  target '***Tests' do
    inherit! :search_paths
  end

end

target '***-tvOS' do

  target '***-tvOSTests' do
    inherit! :search_paths
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # TODO - The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # https://github.com/facebook/react-native/issues/20492
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end
```

**Comment by monoxchd** [comment]
Here are some solutions I tried:

https://github.com/CleverTap/clevertap-segment-ios/issues/3

https://github.com/CleverTap/clevertap-react-native/issues/32

https://stackoverflow.com/questions/55730505/build-error-integrating-clevertap-to-a-reactnative-application

https://github.com/CleverTap/clevertap-react-native/issues/53

**Comment by Aditi3** [comment]
Hi @monoxchd 

Apologizes for the inconvenience caused to you. 

Could you try the following solution? 

1.  Add **use_modular_headers!** in your my Podfile. The **use_modular_headers!** to enable the stricter search paths and module map generation for all of your pods

If the configuration gives conflict with "glog" as mentioned, I suggest either use the below code snippet 
```
 pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
 pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
 pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec' , :modular_headers => false
```
or  use the flag module_headers: true on "Segment-CleverTap", "CleverTap-iOS-SDK" and "RNAnalyticsIntegration-CleverTap"  

2. Navigate to the SEGCleverTapIntegration.m class, replace `#import<CleverTapSDK/CleverTap.h>` with the `@import CleverTapSDK;`

Also, in this scenario you need to import header as `@import CleverTapSDK;` instead of `<CleverTapSDK/CleverTap.h>` in the App Delegate class as well.

Hope this helps.

**Comment by monoxchd** [comment]
@Aditi3 thanks for the quick answer and forgiving me for not returning sooner. I am updating our react-native version to see if this is related to the rn 0.59 version. It seems like on 0.61 the `use_frameworks!` bug is solved and could possibly resolve this error with Clevertap. Will return as soon as it's done.

**Comment by monoxchd** [comment]
@Aditi3 I tried your steps, but ended up forking the project (https://github.com/monoxchd/clevertap-segment-ios) and just changing `#import <CleverTapSDK/CleverTap.h>` to `#import <CleverTap-iOS-SDK/CleverTap.h>` and the project is building correctly. I will keep watching this repository for changes to try and go back to the original project as soon as possible.

**Comment by sdenaci** [comment]
@Aditi3 I am having exactly the same issues as monoxchd. I have tried your solutions. I cannot use frameworks because we use firebase. I have tried :module_headers => true, but this does not work. The only thing that has worked is changing #import <CleverTapSDK/CleverTap.h> to #import <CleverTap-iOS-SDK/CleverTap.h>. I am using the segment react native wrapper.

**Comment by Aditi3** [comment]
Hi @sdenaci 

Not sure why the provided solution doesn't work for you. The same seemed to work rightly in our Test Application.

Having said that, changing #import <CleverTapSDK/CleverTap.h> to #import <CleverTap-iOS-SDK/CleverTap.h> is also one of recommended solution. It means that CleverTapSDK is installed as a static library instead of a dynamic framework.

**Comment by shrmaky** [comment]
I was integrating in React Native `0.65`

In Podfile -

pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native', modular_headers: true
pod 'CleverTap-iOS-SDK', modular_headers: true

In AppDelegate.m, changed to -
```
#import <CleverTap-iOS-SDK/CleverTap.h>
#import <clevertap-react-native/CleverTapReactManager.h>
```

I am able to build now.

**Comment by nkpatnis** [comment]
Tried everything (followed the example also) nothing is working for me,

```objc
#import "CleverTap.h"
#import "CleverTapReactManager.h"

#import <CleverTapSDK/CleverTap.h>
#import <CleverTapReact/CleverTapReactManager.h>

@import CleverTapSDK
@import CleverTapReact

#import <CleverTap-iOS-SDK/CleverTap.h>
#import <clevertap-react-native/CleverTapReactManager.h>
```

even @shrmaky your answer don't know why not working for me, RN 0.66.2

For Debug build following works but not for releaseStaging->
```objc
#import "CleverTap.h"
#import "CleverTapReactManager.h"
```

Please help I am new to iOS.

**Comment by hannanshaik22** [comment]
@nkpatnis Did you manage to resolve this? I am at same state as you.
